name: Waka Readme


on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_COMMIT: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
